add_rules("mode.debug", "mode.release")

target("pq")
    set_kind("binary")
    add_files("src/unittest/pq.c")
    add_files("src/fia/*.c")
    add_files("src/fsort/*.c")
    set_warnings("all", "error")
    set_optimize("none")

target("newfia")
    set_kind("binary")
    add_files("src/unittest/newfia.c")
    add_files("src/fia/*.c")
    set_warnings("all", "error")
    set_optimize("none")


target("app")
    set_kind("binary")
    add_files("src/*.c")
    add_files("src/fia/*.c")
    add_files("src/fsort/*.c")
    add_files("src/analysis/*.c")
    set_warnings("all", "error")
    set_optimize("fastest")

target("app_debug")
    set_kind("binary")
    add_files("src/*.c")
    add_files("src/fia/*.c")
    add_files("src/fsort/*.c")
    add_files("src/analysis/*.c")
    set_warnings("all", "error")
    set_optimize("none")
    add_defines("DEBUG_MODE=1")

